### PR TITLE
Added Table paragraph type

### PR DESCRIPTION
**Pull request by gosia-mlynarczyk**
Relates to [Add 'Table' paragraph type](https://github.com/localgovdrupal/localgov_campaigns/issues/41).

Although the ticket mentions adding Intro text and Additional text fields, I decided to omit them (as the text before / after the table can be added using Text paragraphs - there's no special styling on the Bracknell site that would require having those fields as part of the Table paragraph). But I'm happy to add them if others think they'd be useful here.

I've also added some very basic styling for 'headed' and 'striped' table themes ('minimal; has no styling, will just inherit theme styling for tables). The rest of the styling can be added in themes.

### CODE REVIEW

**Comment by Adnan-cds** [comment]
I was trying to test this locally.  Just as the Github Actions test was saying, the tablefield module was missing despite it being declared in localgov_campaigns/composer.json.  Turned out it was not mentioned in the localgov_campaign_paragraphs.info.yml file.  Once I added it there, all worked fine.  This was a one liner, so I just pushed it myself rather bothering Gosia :)

Tests are still failing though due to broken tests from the unrelated localgov_directories module.  Those localgov_directories tests need urgent attention.  Otherwise all tests will keep failing across the whole project.

FAO @stephen-cox @gosia-mlynarczyk @willguv

**Comment by Adnan-cds** [comment]
Hi Gosia,
We are nearly there.  A few values in the **core.entity_view_display.paragraph.localgov_table.default.yml** and **field.field.paragraph.localgov_table.localgov_table.yml** config files are not matching their schema in tablefield/config/schema/tablefield.schema.yml which is leading to [test failures](https://github.com/localgovdrupal/localgov_campaigns/pull/57/checks?check_run_id=1095495556).  In most cases, it is boolean values mentioned as 0 or 1 rather than true or false.  In one case an integer 1 has been mentioned as a string '1'.  The following diff shows the difference between what the values currently are and what they need to be:
```
diff --git a/modules/localgov_campaigns_paragraphs/config/install/core.entity_view_display.paragraph.localgov_table.default.yml b/modules/localgov_campaigns_paragraphs/config/install/core.entity_view_display.paragraph.localgov_table.default.yml
index 07a9b6c..06491b6 100644
--- a/modules/localgov_campaigns_paragraphs/config/install/core.entity_view_display.paragraph.localgov_table.default.yml
+++ b/modules/localgov_campaigns_paragraphs/config/install/core.entity_view_display.paragraph.localgov_table.default.yml
@@ -16,8 +16,8 @@ content:
     weight: 0
     label: hidden
     settings:
-      row_header: 1
-      column_header: 0
+      row_header: true
+      column_header: false
     third_party_settings: {  }
     type: tablefield
     region: content
diff --git a/modules/localgov_campaigns_paragraphs/config/install/field.field.paragraph.localgov_table.localgov_table.yml b/modules/localgov_campaigns_paragraphs/config/install/field.field.paragraph.localgov_table.localgov_table.yml
index 1d158d3..ff5c5c7 100644
--- a/modules/localgov_campaigns_paragraphs/config/install/field.field.paragraph.localgov_table.localgov_table.yml
+++ b/modules/localgov_campaigns_paragraphs/config/install/field.field.paragraph.localgov_table.localgov_table.yml
@@ -17,12 +17,12 @@ translatable: false
 default_value: {  }
 default_value_callback: ''
 settings:
-  export: 0
-  restrict_rebuild: 0
-  restrict_import: 0
-  lock_values: 0
-  cell_processing: '1'
+  export: false
+  restrict_rebuild: false
+  restrict_import: false
+  lock_values: false
+  cell_processing: 1
   empty_rules:
-    ignore_table_structure: 0
-    ignore_table_header: 0
+    ignore_table_structure: false
+    ignore_table_header: false
 field_type: tablefield
```
Would you mind exporting these files again and checking what values are coming out in your development site?

FAO @gosia-mlynarczyk @finnlewis

**Comment by gosia-mlynarczyk** [comment]
Thanks @Adnan-cds !

Hmm, I've tried exporting those files again, but got the same values as before (so 0 rather than false, etc.) 🤔

**Comment by Adnan-cds** [comment]
> I've tried exporting those files again, but got the same values as before

Thanks for trying Gosia.  I am assuming you are using the LocalGov Lando setup, right?  I am asking because Finn was saying that sometimes PHP version differences can cause issues like these.

@gosia-mlynarczyk @finnlewis

**Comment by gosia-mlynarczyk** [comment]
> I am assuming you are using the LocalGov Lando setup, right?

Yes, I am.

**Comment by Adnan-cds** [comment]
Hi Gosia, I think I have spotted the issue with tablefield: https://www.drupal.org/node/3129884

To avoid this, I have told composer to use the dev-2.x version of tablefield which is based on the tablefield module's development branch.  Please do ```composer require tablefield:dev-2.x``` from the root of your LocalGov site and then fix the values in the config files.   After that run the tests for the **localgov_campaigns_paragraphs** module only: ```lando phpunit web/modules/contrib/localgov_campaigns/modules/localgov_campaigns_paragraphs/tests/src/Functional/CampaignsParagraphsAdministrationTest.php```.  If this test passes, we are good to go.

FAO @gosia-mlynarczyk

**Comment by gosia-mlynarczyk** [comment]
Thank you for looking into this, @Adnan-cds !

I've re-exported the config.

**Review by Adnan-cds — APPROVED** [review]
Looks good.  Thanks a lot @gosia-mlynarczyk :)

**Pull request merged**
