### PR TITLE
Fixed bugs in accordion and tab paragraphs

### PR DESCRIPTION
**Pull request by gosia-mlynarczyk**
- Attached missing accordion library to Tabs paragraph.
- Fixed bug preventing the accordion script from kicking in at certain viewport's width
- Fixed console error

### CODE REVIEW

**Comment by Adnan-cds** [comment]
Hi Gosia,
Good morning :)  How do I test this?

**Comment by gosia-mlynarczyk** [comment]
Hi @Adnan-cds !

I think the best way to test this is to add a Tabs paragraph to a page, and then resize browser window to check whether the Tabs paragraph changes into an accordion at certain width (I think it's set to 767px in the template), and then back to Tabs when the window is resized again to larger width.

**Review by Adnan-cds — APPROVED** [review]
Works in my machine.  Code changes also look good.  Thanks a lot :)

**Comment by gosia-mlynarczyk** [comment]
Thanks @Adnan-cds !

So once I merge this into master, what happens next? I need these bug fixes for the site I'm working on :)

**Comment by Adnan-cds** [comment]
> what happens next? 

Please raise a merge request to merge the **master** branch to the **release** branch.  Once that merge request has been merged, create a release tag.  The last release tag is called 1.0.0-alpha1.  So the new one should be 1.0.0-alpha2.  At this point, if you do a ```composer update localgovdrupal/localgov_campaigns --with-dependencies```, you should be on 1.0.0-alpha2.

**Comment by finnlewis** [comment]
Hi @gosia-mlynarczyk 

Just a quick note to flag that the localgov_campaigns repo is being deprecated in favour of the localgov_subsites repo. 

I realise that we've not have much discussion with Microserve about this, so drawing this to your attention and suggest that it would be good to talk to find out where you are up to with development and how this might affect your work.

Are you using the localgov_campaigns project for the Bracknell site? Is it wasy enough to switch to the localgov_subsites project at this point?

Happy to have a call to discuss.

**Comment by gosia-mlynarczyk** [comment]
Hi @finnlewis 
Yes, we're using localgov_campaigns module for the Bracknell site. We've already built content types (had to tweak campaign pages to make them work for Bracknell), and we've also adapted and styled many of the paragraphs from localgov_campaigns module.

Why is the localgov_campaigns module being deprecated? How different are those two modules?

**Pull request merged**
